### ISSUE TITLE
添加移动设备上的显示安全区

### ISSUE THREAD

**Issue by shoucandanghehe** [26F-Studio/Quatrack#1]
由于目前移动设备多采用圆角屏幕 会导致屏幕边缘部分字体不可见
（同样的问题在techmino上也有
所以这个issue可以认为是针对Zframework的

**Comment by MrZ626** [comment]
哪些

**Comment by MrZ626** [comment]
左上系统状态和左下帧率显示用了love提供的安全区范围，在我的手机上往右避开圆角了
部分设备上love的安全区不对？

**Comment by MrZ626** [comment]
哦看到了 这就

**Comment by shoucandanghehe** [comment]
右上的分数也会被圆角挡住）
