### ISSUE TITLE
Quatrack crashes when trying to change keybinds / 尝试更改按键绑定时 Quatrack 崩溃 (Windows-v0.5.9)

### ISSUE THREAD

**Issue by AFasterSlowpoke** [26F-Studio/Quatrack#27]
I don't speak Chinese, so I used DeepL translator to help me translate the text from English to Simplified Chinese, so some of the Chinese text may be inaccurate. / 我不会说中文，因此我使用了DeepL 翻译器帮助我将文本从英文翻译成简体中文，因此某些中文文本可能不准确。

This bug is pretty self-explanatory. Whenever you go in the settings and try to edit any keybind, Quatrack instantly crashes. / 这个错误不言自明。每当您进入设置并尝试编辑任何按键时，Quatrack都会立即崩溃。

Version used / 使用的版本:
Windows v0.5.9 (OS: Windows 11)

Image / 错误图片
![image](https://github.com/26F-Studio/Quatrack/assets/132897534/c10dfadf-e252-46b9-9353-54b754a1ca35)

**Comment by MrZ626** [comment]
though I don't know what caused it, but there's no problem now
