### ISSUE TITLE
Quatrack Crashes When I Change My Language (Windows/Latest Version)

### ISSUE THREAD

**Issue by RyutoSetsujin** [26F-Studio/Quatrack#30]
![Quatrack_W3Ss05xzhK](https://github.com/26F-Studio/Quatrack/assets/32800772/14976471-1e5f-4620-b0e7-763c4a2fabb4)

**Comment by Rexxt** [comment]
issue personally noticed, patch coming on own repository, pull request arriving

**Comment by MrZ626** [comment]
fixed
