### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by znxofficial** [26F-Studio/Quatrack#31]
尝试在 macOS Sonoma 14.5 (使用 LÖVE ) 和 Xiaomi HyperOS 1.0.10 均报错启动不能。
不知何故，求解。
<img width="1307" alt="截屏2024-06-01 19 10 59" src="https://github.com/26F-Studio/Quatrack/assets/57528029/60afb793-78b9-46a2-87e7-b107d21d3c31">
![Screenshot_2024-06-01-19-11-43-748_org f26_studio](https://github.com/26F-Studio/Quatrack/assets/57528029/c2099e7c-0954-463e-870f-d497313e5ce1)

**Comment by MrZ626** [comment]
安卓的报错修好了，mac的是比较底层的问题，我这还真修不了，就先close吧
